// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxs7038-eyj5SWaAVOtxAHw0Q1Fx4bF_g',
    appId: '1:184043914033:web:4f78fe63664effd7206610',
    messagingSenderId: '184043914033',
    projectId: 'classic-b1a70',
    authDomain: 'classic-b1a70.firebaseapp.com',
    storageBucket: 'classic-b1a70.appspot.com',
    measurementId: 'G-9NCQYLS7VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP_w9FTB3LeQtEaHXMK5ZXD4pBrI50wRc',
    appId: '1:184043914033:android:5c179225f5bd30df206610',
    messagingSenderId: '184043914033',
    projectId: 'classic-b1a70',
    storageBucket: 'classic-b1a70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcR-lr7RXVwuzKDzvlYuFiqnPP1Zxp30g',
    appId: '1:184043914033:ios:6c156fe0669e3ad7206610',
    messagingSenderId: '184043914033',
    projectId: 'classic-b1a70',
    storageBucket: 'classic-b1a70.appspot.com',
    iosClientId: '184043914033-6eetm3lb72vnti46qmsv68vo8elvpfj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.classic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcR-lr7RXVwuzKDzvlYuFiqnPP1Zxp30g',
    appId: '1:184043914033:ios:6c156fe0669e3ad7206610',
    messagingSenderId: '184043914033',
    projectId: 'classic-b1a70',
    storageBucket: 'classic-b1a70.appspot.com',
    iosClientId: '184043914033-6eetm3lb72vnti46qmsv68vo8elvpfj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.classic',
  );
}
